name: assert

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          FILTER_REGEX_INCLUDE: src/.*
          VALIDATE_EDITORCONFIG: true
          VALIDATE_JAVA: true
  assemble:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Assemble outputs
        run: echo "TODO assemble outputs"
  javadoc:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate javadoc
        run: echo "TODO generate javadoc"
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "TODO run tests"
